<a href="https://colab.research.google.com/github/kr7/udm/blob/main/udm_normalizalas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Standard normalizálás**

In [2]:
import numpy as np

In [3]:
data = np.array( [ [1.6, 18], [1.85, 23], [2.10, 26], [1.75, 52] ])

In [4]:
data

array([[ 1.6 , 18.  ],
       [ 1.85, 23.  ],
       [ 2.1 , 26.  ],
       [ 1.75, 52.  ]])

In [5]:
np.std(data[:,0])

np.float64(0.18200274723201296)

In [6]:
np.mean(data[:,0])

np.float64(1.8250000000000002)

In [7]:
data[:,0] = (data[:,0]-np.mean(data[:,0]))/np.std(data[:,0])

In [8]:
data

array([[-1.23624508, 18.        ],
       [ 0.13736056, 23.        ],
       [ 1.5109662 , 26.        ],
       [-0.41208169, 52.        ]])

In [9]:
data[:,1] = (data[:,1]-np.mean(data[:,1]))/np.std(data[:,1])

In [10]:
data

array([[-1.23624508, -0.89285225],
       [ 0.13736056, -0.51291512],
       [ 1.5109662 , -0.28495284],
       [-0.41208169,  1.69072021]])

**Min-max normalizálás**

In [11]:
data = np.array( [ [1.6, 18], [1.85, 23], [2.10, 26], [1.75, 52] ])

In [12]:
data

array([[ 1.6 , 18.  ],
       [ 1.85, 23.  ],
       [ 2.1 , 26.  ],
       [ 1.75, 52.  ]])

In [13]:
data[:,0] = (data[:,0]-np.min(data[:,0]))/(np.max(data[:,0])-np.min(data[:,0]))

In [ ]:
data

array([[0.        , 0.        ],
       [0.5       , 0.14705882],
       [1.        , 0.23529412],
       [0.3       , 1.        ]])

In [14]:
data[:,1] = (data[:,1]-np.min(data[:,1]))/(np.max(data[:,1])-np.min(data[:,1]))

In [15]:
data

array([[0.        , 0.        ],
       [0.5       , 0.14705882],
       [1.        , 0.23529412],
       [0.3       , 1.        ]])